title:             Jekyll Swagger Portal
email:             anderson.braz@gmail.com
description:       A quick start project for building swagger documentation in a form of API Portal
author:            Mr. Braz

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

collections:
  apis:
    output: true

