title:             Jekyll Swagger Portal
email:             anderson.braz@gmail.com
description:       A quick start project for building swagger documentation in a form of API Portal
author:            Mr. Braz
baseurl:           "/jekyll-swagger/"
url:               "https://mrbraztech.github.io/"

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
